--- 
title: "A Minimal rTorch Tutorial"
author: "Alfonso R. Reyes"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal tutorial of using the `rTorch` package to have fun while doing machine learning. This book was produced with `bookdown`."
---

# Prerequisites

This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2$.

The **rTorch** package can be installed from CRAN or Github:

```{r eval=FALSE}
install.packages("rTorch")
# or the development version
# devtools::install_github("f0nzie/rTorch")
```


To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.name/tinytex/>.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'rTorch','bookdown', 'knitr', 'rmarkdown'), 
  'packages.bib')
```
