# Convolutional Network with MNIST digits

## Complete training
Source: https://github.com/floydhub/mnist/blob/master/main.py

Original code taken from tutorial: https://ags.cs.uni-kl.de/fileadmin/inf_ags/2dip-ss19/Intro_CNN_SS2019.pdf. The `Net()` class does not work.

Modified based on code: https://github.com/floydhub/mnist/blob/master/main.py


```{r}
library(rTorch)
```

## Python libraries

```{python}
from __future__ import print_function
import argparse
import os
import numpy
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision.datasets import ImageFolder
from PIL import Image
import numpy as np
from torchvision import datasets, transforms
from torch.autograd import Variable
```

## Parameters

```{python}
seed = 1
torch.manual_seed(seed)
dataroot = "./data"
evalf = "/home/msfz751/mnist_digits_test"   # path to evaluate sample

no_cuda = True
use_cuda = not no_cuda and torch.cuda.is_available()
batch_size = 64
test_batch_size = 1000  
lr = 0.01           # default = 0.01
momentum = 0.5      # default = 0.5
log_interval = 40   # default = 10
epochs = 10          # default = 10

# From MNIST to Tensor
kwargs = {'num_workers': 1, 'pin_memory': True} if use_cuda else {}
```


## Set up data

```{python}
train_loader = torch.utils.data.DataLoader(
    datasets.MNIST(
                    root=dataroot, 
                    train=True, 
                    download=True,
                    transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                        ])),
                    batch_size=batch_size, shuffle=True, **kwargs)

test_loader = torch.utils.data.DataLoader(
    datasets.MNIST(
                root=dataroot, 
                train=False, 
                transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
                batch_size=test_batch_size, shuffle=True, **kwargs)
```

## Set up model

```{python, setup-net}
# Source: https://github.com/floydhub/mnist/blob/master/main.py

class Net(nn.Module):
    """ConvNet -> Max_Pool -> RELU -> ConvNet -> Max_Pool -> RELU -> FC -> 
        RELU -> FC -> SOFTMAX
    """
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.fc1 = nn.Linear(4*4*50, 500)
        self.fc2 = nn.Linear(500, 10)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(-1, 4*4*50)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)
        
model = Net()        
print(model)
```

```{python}
optimizer = optim.SGD(model.parameters(), lr=lr, momentum=momentum)
```

## Train model

```{python, train-dataset}
def train(model, train_loader, optimizer, epoch, log_interval):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))
            print('{{"metric": "Train - NLL Loss", "value": {}}}'.format(
        loss.item()))
            sys.stdout.flush()


def test(model, test_loader, epoch):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            output = model(data)
            test_loss += F.nll_loss(output, target, reduction='sum').item() # sum up batch loss
            pred = output.argmax(dim=1, keepdim=True) # get the index of the max log-probability
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))
    print('{{"metric": "Eval - NLL Loss", "value": {}, "epoch": {}}}'.format(
        test_loss, epoch))
    print('{{"metric": "Eval - Accuracy", "value": {}, "epoch": {}}}'.format(
        100. * correct / len(test_loader.dataset), epoch))
    sys.stdout.flush()
```


## Test custom images

```{python, test-custom-images}
def test_image():
    def get_images_name(folder):
        """Create a generator to list images name at evaluation time"""
        onlyfiles = [f for f in os.listdir(folder) if os.path.isfile(os.path.join(folder, f))]
        onlyfiles = sorted(onlyfiles)
        for f in onlyfiles:
            yield f
    
    
    def pil_loader(path):
        """Load images from subfolder, convert to greyscale and resized it as squared"""
        with open(path, 'rb') as f:
            with Image.open(f) as img:
                sqrWidth = np.ceil(np.sqrt(img.size[0]*img.size[1])).astype(int)
                return img.convert('L').resize((sqrWidth, sqrWidth))
            
            
    eval_loader = torch.utils.data.DataLoader(ImageFolder(root=evalf, transform=transforms.Compose([
                           transforms.Resize(28),
                           transforms.CenterCrop(28),
                           transforms.ToTensor(),
                           transforms.Normalize((0.1307,), (0.3081,))
                       ]), loader=pil_loader), batch_size=1, **kwargs)   
                       
    # Name generator
    names = get_images_name(os.path.join(evalf, "images"))
    mute = model.eval()     
    
    # perform the comparison of the model vs an image sample
    with torch.no_grad():
        for obj in eval_loader:
            # print(obj)
            x, target = obj
            output = model(x)
            label = output.argmax(dim=1, keepdim=True).item()
            filename = next(names)
            print("Image %15s for digit %3s, Classified as: %3d" % (filename, filename[0], label)) 
            
```

```{python}
# Train + Test per epoch
for epoch in range(1, epochs + 1):
    train(model, train_loader, optimizer, epoch, log_interval = 100)
    test(model, test_loader, epoch)
```

```{python}
test_image()
```

```
epochs=5
Image      0-1621.png for digit   0, Classified as:   0
Image       0-490.png for digit   0, Classified as:   0
Image       0-611.png for digit   0, Classified as:   0
Image      1-2182.png for digit   1, Classified as:   1
Image      1-2753.png for digit   1, Classified as:   1
Image      1-2946.png for digit   1, Classified as:   1
Image      2-1551.png for digit   2, Classified as:   2
Image        2-28.png for digit   2, Classified as:   2
Image       2-321.png for digit   2, Classified as:   7
Image     2-39228.png for digit   2, Classified as:   2
Image      3-1114.png for digit   3, Classified as:   3
Image      3-2308.png for digit   3, Classified as:   3
Image      3-2927.png for digit   3, Classified as:   2
Image      3-4443.png for digit   3, Classified as:   3
Image       3-464.png for digit   3, Classified as:   3
Image      4-2130.png for digit   4, Classified as:   9
Image       4-447.png for digit   4, Classified as:   4
Image       4-511.png for digit   4, Classified as:   4
Image       5-138.png for digit   5, Classified as:   5
Image      5-1393.png for digit   5, Classified as:   3
Image      5-2237.png for digit   5, Classified as:   5
Image      6-1296.png for digit   6, Classified as:   6
Image      6-1569.png for digit   6, Classified as:   6
Image       7-124.png for digit   7, Classified as:   7
Image        7-60.png for digit   7, Classified as:   7
Image       7-689.png for digit   7, Classified as:   7
Image      8-1033.png for digit   8, Classified as:   8
Image      8-4497.png for digit   8, Classified as:   7
Image      8-4513.png for digit   8, Classified as:   8
Image      9-3060.png for digit   9, Classified as:   7
Image       9-320.png for digit   9, Classified as:   9
```


```
epochs=1
Image      0-1621.png for digit   0, Classified as:   6
Image       0-490.png for digit   0, Classified as:   0
Image       0-611.png for digit   0, Classified as:   0
Image      1-2182.png for digit   1, Classified as:   2
Image      1-2753.png for digit   1, Classified as:   1
Image      1-2946.png for digit   1, Classified as:   1
Image      2-1551.png for digit   2, Classified as:   2
Image        2-28.png for digit   2, Classified as:   2
Image       2-321.png for digit   2, Classified as:   7
Image     2-39228.png for digit   2, Classified as:   2
Image      3-1114.png for digit   3, Classified as:   3
Image      3-2308.png for digit   3, Classified as:   3
Image      3-2927.png for digit   3, Classified as:   2
Image      3-4443.png for digit   3, Classified as:   3
Image       3-464.png for digit   3, Classified as:   3
Image      4-2130.png for digit   4, Classified as:   9
Image       4-447.png for digit   4, Classified as:   4
Image       4-511.png for digit   4, Classified as:   4
Image       5-138.png for digit   5, Classified as:   5
Image      5-1393.png for digit   5, Classified as:   3
Image      5-2237.png for digit   5, Classified as:   5
Image      6-1296.png for digit   6, Classified as:   6
Image      6-1569.png for digit   6, Classified as:   4
Image       7-124.png for digit   7, Classified as:   7
Image        7-60.png for digit   7, Classified as:   7
Image       7-689.png for digit   7, Classified as:   9
Image      8-1033.png for digit   8, Classified as:   8
Image      8-4497.png for digit   8, Classified as:   7
Image      8-4513.png for digit   8, Classified as:   8
Image      9-3060.png for digit   9, Classified as:   7
Image       9-320.png for digit   9, Classified as:   9
```

## Glossary

* An `nn.Module` contains layers, and a method `forward(input)` that returns the output.

* The learnable parameters of a model are returned by `net.parameters()`.

* `torch.Tensor` - A multi-dimensional array with support for autograd
operations like `backward()`. Also holds the gradient w.r.t. the tensor.

* `nn.Module` - Neural network module. Convenient way of encapsulating
parameters, with helpers for moving them to GPU, exporting, loading, etc.

* `nn.Parameter` - A kind of Tensor, that is automatically registered as a
parameter when assigned as an attribute to a `Module`.


